### ISSUE TITLE
IndexError: list index out of range

### ISSUE THREAD

**Issue by jwang44** [cifkao/ismir2019-music-style-translation#1]
Hi, I get a 'IndexError: list index out of range' error when I try to train the model by running the following command inside the _'experiments'_ directory.
`python -m ismir2019_cifka.models.roll2seq_style --logdir all2bass train`

![屏幕快照 2019-08-26 22 31 07](https://user-images.githubusercontent.com/54256124/63697946-72c59100-c850-11e9-8e86-305652e3412a.png)

I used 60 of the songs in 2 different styles as training set. Obviously too few but I'm just trying to get this training process going. The data is prepared following the 'README' steps. 
Maybe you could give me a hand?

**Comment by cifkao** [comment]
Sorry for the late response, I missed the issue.

This probably means your validation dataset is empty. You can try providing (a part of) the training data as validation data to make the trainer happy.

**Comment by jwang44** [comment]
Thanks for your kind reply! There's another problem though. I find it quite time consuming to generate 3500 songs in 70 different styles with BIAB software. Maybe I could find your training dataset somewhere?

**Comment by cifkao** [comment]
I'm afraid cannot make the dataset publicly available, but feel free to send me your request by email along with your name, the name of your institution and the purpose for which you want to use the dataset.

Also, BIAB has batch processing functionality (change style / convert to MIDI) that you can look at.
