### ISSUE TITLE
Is the MIDI data openly avaliable?

### ISSUE THREAD

**Issue by lukewys** [cifkao/ismir2019-music-style-translation#3]
Dear authors, I am very interested in your work. Can I have access to the band in a box MIDI data?

Thanks in advance.

**Comment by cifkao** [comment]
We did not release the dataset publicly, but I encourage you to send us your request by email along with your name, the name of your institution and the purpose for which you would like to use the data.

We are also planning to release a larger, fully synthetic dataset in the near future.

**Comment by lukewys** [comment]
Thank you so much! I will send you an email requesting for data. Thanks again!

**Comment by cifkao** [comment]
As promised, we are now releasing the [Groove2Groove MIDI Dataset](https://groove2groove.telecom-paris.fr/#Dataset).
